[package]
name = "terminal-clock"
version = "0.1.0"
authors = ["msk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
figlet-rs = "0.1.3"
regex = "1.4.5"
termion = "1.5.6"
